// <auto-generated />
using System;
using CasherSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CasherSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CasherSystem.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Barcode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Color")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("CostPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("SellPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Size")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("counterOfSell")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Barcode = "TSH001",
                            Color = "أزرق",
                            CostPrice = 15.00m,
                            IsActive = true,
                            Name = "قميص قطني",
                            Quantity = 50,
                            SellPrice = 25.00m,
                            Size = "M",
                            counterOfSell = 0
                        },
                        new
                        {
                            Id = 2,
                            Barcode = "JEA001",
                            Color = "أزرق",
                            CostPrice = 35.00m,
                            IsActive = true,
                            Name = "جينز",
                            Quantity = 30,
                            SellPrice = 60.00m,
                            Size = "L",
                            counterOfSell = 0
                        },
                        new
                        {
                            Id = 3,
                            Barcode = "HOO001",
                            Color = "أسود",
                            CostPrice = 40.00m,
                            IsActive = true,
                            Name = "هودي",
                            Quantity = 20,
                            SellPrice = 75.00m,
                            Size = "XL",
                            counterOfSell = 0
                        },
                        new
                        {
                            Id = 4,
                            Barcode = "DRE001",
                            Color = "أحمر",
                            CostPrice = 25.00m,
                            IsActive = true,
                            Name = "فستان صيفي",
                            Quantity = 15,
                            SellPrice = 45.00m,
                            Size = "S",
                            counterOfSell = 0
                        },
                        new
                        {
                            Id = 5,
                            Barcode = "SNE001",
                            Color = "أبيض",
                            CostPrice = 50.00m,
                            IsActive = true,
                            Name = "حذاء رياضي",
                            Quantity = 25,
                            SellPrice = 90.00m,
                            Size = "42",
                            counterOfSell = 0
                        },
                        new
                        {
                            Id = 6,
                            Barcode = "SHI001",
                            Color = "أبيض",
                            CostPrice = 30.00m,
                            IsActive = true,
                            Name = "قميص رسمي",
                            Quantity = 40,
                            SellPrice = 55.00m,
                            Size = "L",
                            counterOfSell = 0
                        },
                        new
                        {
                            Id = 7,
                            Barcode = "PAN001",
                            Color = "رمادي",
                            CostPrice = 45.00m,
                            IsActive = true,
                            Name = "بنطلون كاجوال",
                            Quantity = 35,
                            SellPrice = 80.00m,
                            Size = "M",
                            counterOfSell = 0
                        },
                        new
                        {
                            Id = 8,
                            Barcode = "JAC001",
                            Color = "بني",
                            CostPrice = 80.00m,
                            IsActive = true,
                            Name = "جاكيت شتوي",
                            Quantity = 12,
                            SellPrice = 150.00m,
                            Size = "XL",
                            counterOfSell = 0
                        });
                });

            modelBuilder.Entity("CasherSystem.Models.Purchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PaidAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RemainingAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("CasherSystem.Models.Return", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("SaleId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalRefund")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("UserInfoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SaleId");

                    b.HasIndex("UserInfoId");

                    b.ToTable("Returns");
                });

            modelBuilder.Entity("CasherSystem.Models.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Discount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("SecretCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("CasherSystem.Models.UserInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PhoneNumber = "01234567890",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            PhoneNumber = "01234567891",
                            Username = "seller1"
                        },
                        new
                        {
                            Id = 3,
                            PhoneNumber = "01234567892",
                            Username = "seller2"
                        });
                });

            modelBuilder.Entity("ProductReturn", b =>
                {
                    b.Property<int>("ReturnsId")
                        .HasColumnType("int");

                    b.Property<int>("productsId")
                        .HasColumnType("int");

                    b.HasKey("ReturnsId", "productsId");

                    b.HasIndex("productsId");

                    b.ToTable("ProductReturn");
                });

            modelBuilder.Entity("CasherSystem.Models.Purchase", b =>
                {
                    b.OwnsOne("CasherSystem.Models.Supplier", "Supplier", b1 =>
                        {
                            b1.Property<int>("PurchaseId")
                                .HasColumnType("int");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("PhoneNumber")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.HasKey("PurchaseId");

                            b1.ToTable("Purchases");

                            b1.WithOwner()
                                .HasForeignKey("PurchaseId");
                        });

                    b.Navigation("Supplier")
                        .IsRequired();
                });

            modelBuilder.Entity("CasherSystem.Models.Return", b =>
                {
                    b.HasOne("CasherSystem.Models.Sale", "Sale")
                        .WithMany("Returns")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CasherSystem.Models.UserInfo", null)
                        .WithMany("Returns")
                        .HasForeignKey("UserInfoId");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("CasherSystem.Models.Sale", b =>
                {
                    b.HasOne("CasherSystem.Models.Product", null)
                        .WithMany("Sales")
                        .HasForeignKey("ProductId");

                    b.HasOne("CasherSystem.Models.UserInfo", "User")
                        .WithMany("Sales")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProductReturn", b =>
                {
                    b.HasOne("CasherSystem.Models.Return", null)
                        .WithMany()
                        .HasForeignKey("ReturnsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CasherSystem.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("productsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CasherSystem.Models.Product", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("CasherSystem.Models.Sale", b =>
                {
                    b.Navigation("Returns");
                });

            modelBuilder.Entity("CasherSystem.Models.UserInfo", b =>
                {
                    b.Navigation("Returns");

                    b.Navigation("Sales");
                });
#pragma warning restore 612, 618
        }
    }
}
